test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.subdir", "change_url"]  # The test IDs to be used in only/exclude statements are: install.root, install.subdir, install.nourl, install.multi, backup_restore, upgrade, upgrade.someCommitId change_url

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.welcometext="Welcome to my Mumble server"
	args.registername="Root"