#!/bin/bash
exec > >(tee /tmp/mumble-install.log)
exec 2>&1
app=mumbleserver

# Retrieve arguments
admin=$1
server_password=$2
welcometext=$3
port=$4
registerName=$5

mumble_conf=/etc/mumble-server.ini
# Check user
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
if [[ ! $? -eq 0 ]]; then
echo "Wrong user"
	exit 1
fi
# Check port availability
sudo yunohost app checkport $port
if [[ ! $? -eq 0 ]]; then
	exit 1
fi


# Save app settings
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app port -v "$port"

# install via apt-get
sudo apt-get update > /dev/null 2>&1
sudo apt-get install -y mumble-server > /dev/null 2>&1

#configuring with given settings
sudo sed -i "s/welcometext=.*/welcometext=$welcometext/g" $mumble_conf
sudo sed -i "s/port=.*/port=$port/g" $mumble_conf
sudo sed -i "s/serverpassword=.*/serverpassword=$server_password/g" $mumble_conf
sudo sed -i "s/*serverpassword=.*/registerName=$registerName/g" $mumble_conf

#generating random password for super-user
su_passwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')

#save superuser password
sudo yunohost app setting $app superuser_password -v "$su_passwd"
#open port in firewall
sudo yunohost firewall allow Both $port > /dev/null 2>&1

#starting mumble server 
sudo /etc/init.d/mumble-server start

#setting super-user password
sudo murmurd -supw $su_passwd
#restart mumble server
sudo /etc/init.d/mumble-server restart

