#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
server_password=$YNH_APP_ARG_SERVER_LOGIN_PASSWORD
su_passwd=$YNH_APP_ARG_PASSWORD
welcometext=$YNH_APP_ARG_WELCOMETEXT
port=$YNH_APP_ARG_PORT
registerName=$YNH_APP_ARG_REGISTERNAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"

# Check port availability

yunohost app checkport "$port"
if [[ ! $? -eq 0 ]]; then
	ynh_die "Port is not available"
fi

# Check if su_password is not empty
if [[ -z "$su_passwd" ]]; then
	ynh_die "Password is not set"
fi

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

# Save app settings
ynh_app_setting_set "$app" port            "$port"
ynh_app_setting_set "$app" server_password "$server_password"
ynh_app_setting_set "$app" su_passwd       "$su_passwd"
ynh_app_setting_set "$app" welcometext     "$welcometext"
ynh_app_setting_set "$app" registerName    "$registerName"

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================

# Open port in firewall
yunohost firewall allow Both "$port"

#=================================================
# INSTALL DEPENDENCIES
#=================================================

# Install Mumble Debian package via apt
ynh_install_app_dependencies mumble-server

#=================================================
# SPECIFIC SETUP
#=================================================
# mumble server conf.ini
#=================================================

mkdir -p "$final_path"
ynh_app_setting_set "$app" final_path "$final_path"

# Configuring with given settings
mumble_conf="$final_path/mumble-server.ini"

cp ../conf/mumble-server.ini "$mumble_conf"

ynh_replace_string "__FINALPATH__" "$final_path"     "$mumble_conf"
ynh_replace_string "__APP__"      "$app"             "$mumble_conf"
ynh_replace_string "__WELCOME__"  "$welcometext"     "$mumble_conf"
ynh_replace_string "__PORT__"     "$port"            "$mumble_conf"
ynh_replace_string "__SRV_PWD__"  "$server_password" "$mumble_conf"
ynh_replace_string "__REGISTER__" "$registerName"    "$mumble_conf"

#=================================================
# SETUP SYSTEMD
#=================================================

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# STORE THE CHECKSUM OF THE CONFIG FILE
#=================================================

ynh_store_file_checksum "$mumble_conf"

#=================================================
# Start services
#=================================================

mkdir -p /var/run/mumble-server/
murmurd -ini "$mumble_conf" -supw "$su_passwd"

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chmod -R 770 "$final_path"
chown -R :mumble-server "$final_path"

#=================================================
# Disable default server installed by Debian's package
#=================================================

systemctl stop mumble-server
systemctl disable mumble-server

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

# Add Mumble as a YunoHost service
yunohost service add "$app" -l "/var/log/mumble-server/$app.log"

systemctl restart "$app"
