#!/bin/bash

app=mumbleserver

# Getting port used by mumble to close it
port=$(sudo yunohost app setting $app port)

# Uninstall mumble and its dependencies
sudo apt-get autoremove -y mumble-server > /dev/null 2>&1

# Close ports
sudo yunohost firewall disallow Both $port > /dev/null 2>&1
sudo yunohost firewall disallow --ipv6 Both $port > /dev/null 2>&1

# Removing config file
sudo rm -f /etc/mumble-server.ini

# Remove mumble-server service
sudo yunohost service remove mumble-server
