#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e _common.sh ]; then
	# Get the _common.sh file if it's not in the current directory
	cp ../settings/scripts/_common.sh ./_common.sh
	chmod a+rx _common.sh
fi
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get "$app" final_path)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================

test ! -d "$final_path" \
	|| ynh_die "There is already a directory: $final_path "

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

ynh_restore_file "$final_path"

#=================================================
# SPECIFIC RESTORATION
#=================================================
# REINSTALL DEPENDENCIES
#=================================================

# Define and install dependencies
ynh_install_app_dependencies mumble-server mailutils

#=================================================
# RESTORE USER RIGHTS
#=================================================

# Restore permissions on app files
chmod -R 770 "$final_path"
chown -R :mumble-server "$final_path"
# Prevent "PID file /var/run/mumble-server/*.pid not readable (yet?) after start."
chown mumble-server /var/run/mumble-server/

#=================================================
# Add user to ssl-cert so it can read certificates
#=================================================

usermod --append --groups ssl-cert mumble-server

#=================================================
# Disable default server installed by Debian's package
#=================================================

systemctl stop mumble-server
systemctl disable mumble-server

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

# Add Mumble as a YunoHost service
yunohost service add "$app" -l "/var/log/mumble-server/$app.log"

#=================================================
# RESTORE SYSTEMD
#=================================================

ynh_restore_file "/etc/systemd/system/$app.service"
systemctl enable "$app.service"

systemctl restart "$app"
