#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..."

ynh_systemd_action --service_name=$app --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# test old time
if [ -z "$server_password" ]; then
	old_mumble_conf="/etc/mumble-server.ini"

	server_password=$(cat "$old_mumble_conf" \
		| grep "serverpassword=" \
		| sed "s/serverpassword=//")

	welcometext=$(cat "$old_mumble_conf" \
		| grep "welcometext=" \
		| sed "s/welcometext=//")

	registername=$(cat "$old_mumble_conf" \
		| grep "registerName=" \
		| sed "s/registername=//")

	# we don't know what the previous password was, let's regenerate it
	su_passwd=$(ynh_string_random)

	domain=$(yunohost domain list \
		| grep "\- " \
		| head -1 \
		| sed -r "s/.* (([a-z])*\.([a-z])*).*/\1/g")

#REMOVEME? 	ynh_app_setting_set --app=$app --key=server_password --value=$server_password
	ynh_app_setting_set --app=$app --key=welcometext     --value=$welcometext
	ynh_app_setting_set --app=$app --key=registername    --value=$registername
	ynh_app_setting_set --app=$app --key=su_passwd       --value=$su_passwd
#REMOVEME? 	ynh_app_setting_set --app=$app --key=domain          --value=$domain

	systemctl stop mumble-server
	dpkg-reconfigure mumble-server --frontend=Noninteractive
	systemctl stop mumble-server
	systemctl disable mumble-server --quiet
fi

# Fix SSO issue
# https://github.com/YunoHost-Apps/mumbleserver_ynh/issues/19
if [ -z "$domain" ]; then
#REMOVEME? 	domain=$(ynh_app_setting_get "$app" domain_mumble)
#REMOVEME? 	ynh_app_setting_set "$app" domain "$domain"
	ynh_app_setting_delete "$app" domain_mumble
fi

# Fix SSO issue
# https://github.com/YunoHost-Apps/mumbleserver_ynh/issues/19
if [ -z "$no_sso" ]; then
	ynh_app_setting_set "$app" no_sso "true"
fi

# Fix multi installation
if [ -z "$instance_id" ]; then
	instance_id=$YNH_APP_INSTANCE_NUMBER
	ynh_app_setting_set "$app" instance_id "$instance_id"
fi

if [ -z "$registername" ]; then
#REMOVEME?     registername=$(ynh_app_setting_get "$app" registerName)
    ynh_app_setting_set "$app" registername "$registername"
    ynh_app_setting_delete "$app" registerName
fi

#=================================================
# SPECIFIC UPGRADE
#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating a configuration file..." --weight=1

mkdir -p $install_dir

# Configuring with given settings
mumble_conf="$install_dir/mumble-server.ini"

ynh_add_config --template="../conf/mumble-server.ini" --destination="$mumble_conf"

chmod -R 770 "$install_dir"
chown -R :mumble-server "$install_dir"

#=================================================
# Add user to ssl-cert so it can read certificates
#=================================================

usermod --append --groups ssl-cert mumble-server

#=================================================
# Set SuperUser password
#=================================================

# || true temporarily to ignore a bug in murmurd 1.3.0
# https://github.com/mumble-voip/mumble/issues/3911
murmurd -ini "$mumble_conf" -supw "$su_passwd" "$instance_id" || true

#=================================================
# Disable default server installed by Debian's package
#=================================================

systemctl stop mumble-server
systemctl disable mumble-server --quiet

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Upgrading systemd configuration..." --weight=2

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# GENERIC FINALIZATION
#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1

# Add Mumble as a YunoHost service
yunohost service add $app --description="Mumble server" --log="/var/log/mumble-server/$app.log" --needs_exposed_ports="$port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=3

ynh_systemd_action --service_name=$app --action=restart --log_path="/var/log/mumble-server/$app.log"

#=================================================
# SEND README TO ADMIN
#=================================================

message="
Mumbleserver was updated!

Port                   : $port
Password to join server: $server_password
SuperUser Password     : $su_passwd
Welcome text           : $welcometext
Root channel (your Mumble server name): $registername
Final path (where to find your files) : $install_dir
Mumble configuration file             : $mumble_conf

Note about config file: this package will regenerate the config file on upgrade.
If you changed it manually and upgrade mumble, you'll find a backup in /home/yunohost.conf/backup/var/www/mumbleserver/.

Are you facing an issue, want to improve this app or say thank you?
Please open a new issue in this project: https://github.com/YunoHost-Apps/mumbleserver_ynh
"
ynh_send_readme_to_admin "$message"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
